export var SIMULA = {
  tiposUsuario:[
    {id:"01", name:"Comerciante 1"},
    {id:"02", name:"Comerciante 2"},
    {id:"03", name:"Comerciante 3"},
    {id:"04", name:"Comerciante 4"},
    {id:"05", name:"Comerciante 5"},
    {id:"06", name:"Comerciante 6"}
  ],
  productos:[
    {id:'01',name:"Producto 1", image:"./assets/image/bat.png", desciption:"Descipcion 1", points:[2,2,2,1,0]},
    {id:'02',name:"Producto 2", image:"./assets/image/bat.png", desciption:"Descipcion 2", points:[2,2,2,2,1]},
    {id:'03',name:"Producto 3", image:"./assets/image/bat.png", desciption:"Descipcion 3", points:[2,2,2,0,0]},
    {id:'04',name:"Producto 4", image:"./assets/image/bat.png", desciption:"Descipcion 4", points:[2,2,1,0,0]},
    {id:'05',name:"Producto 5", image:"./assets/image/bat.png", desciption:"Descipcion 5", points:[2,2,2,1,0]}
  ],
  catergorias:[
    {id:'C01', name: 'Fibras', padre: 'raiz'},
    {id:'C02', name: 'Fibra acrílica', padre: 'Fibras'},
    {id:'C03', name: 'Fibra de aramida', padre: 'Fibras'},
    {id:'C04', name: 'Fibra de bambu', padre: 'Fibras'},
    {id:'C05', name: 'Fibra química', padre: 'Fibras'},
    {id:'C06', name: 'Fibra de cáñamo', padre: 'Fibras'},
    {id:'C07', name: 'Fibra hueca', padre: 'Fibras'},
    {id:'C08', name: 'Fibra de yute', padre: 'Fibras'},
    {id:'C09', name: 'Fibra de lino', padre: 'Fibras'},
    {id:'C10', name: 'Fibra Modacrílica', padre: 'Fibras'},
    {id:'C11', name: 'Fibra de nailon', padre: 'Fibras'},
    {id:'C12', name: 'Fibra de poliester', padre: 'Fibras'},
    {id:'C13', name: 'Fibra de polipropileno', padre: 'Fibras'},
    {id:'C14', name: 'Algodón en bruto', padre: 'Fibras'},
    {id:'C15', name: 'Fibra de poliéster reciclado', padre: 'Fibras'},
    {id:'C16', name: 'Fibra de seda', padre: 'Fibras'},
    {id:'C17', name: 'Fibra de grapas', padre: 'Fibras'},
    {id:'C18', name: 'Fibra sintética', padre: 'Fibras'},
    {id:'C19', name: 'UHMWPE Fibra', padre: 'Fibras'},
    {id:'C20', name: 'Otras fibras', padre: 'Fibras'},
    {id:'C21', name: 'Fibra de viscosa', padre: 'Fibras'},
    {id:'C22', name: 'Fibra de lana', padre: 'Fibras'},
    {id:'C23', name: 'Fibras innovadoras Hilaturas', padre: 'raiz'},
    {id:'C24', name: 'Hilado mezclado acrílico', padre: 'Fibras innovadoras Hilaturas'},
    {id:'C25', name: 'Hilo de acrílico', padre: 'Fibras innovadoras Hilaturas'},
    {id:'C26', name: 'Hilo mezclado de bambú', padre: 'Fibras innovadoras Hilaturas'},
    {id:'C27', name: 'Hilado de fibra de bambú', padre: 'Fibras innovadoras Hilaturas'},
    {id:'C28', name: 'Tela', padre: 'raiz'},
    {id:'C29', name: 'Tela acrílica', padre: 'Tela'},
    {id:'C30', name: 'Tela de fibra de bambú', padre: 'Tela'},
    {id:'C31', name: 'Tela de fibra de carbono', padre: 'Tela'},
    {id:'C32', name: 'Tela de cachemira', padre: 'Tela'},
    {id:'C33', name: 'Tela de algodón', padre: 'Tela'},
    {id:'C34', name: 'Cuero, piel y plumas', padre: 'raiz'},
    {id:'C29', name: 'Cuero', padre: 'Cuero, piel y plumas'},
    {id:'C30', name: 'Piel de vaca', padre: 'Cuero, piel y plumas'},
    {id:'C31', name: 'Piel genuina', padre: 'Cuero, piel y plumas'},
    {id:'C32', name: 'Productos de cuero', padre: 'Cuero, piel y plumas'},
    {id:'C33', name: 'Cuero sintético PU', padre: 'Cuero, piel y plumas'},
  ],
  usuario: [
    {_id: '1', nombre: 'usuario 1', tipo: "Comerciante", correo: 'uno@correo.com', telefono: '0123465789', password:"123456"},
    {_id: '2', nombre: 'usuario 2', tipo: "Comerciante", correo: 'dos@correo.com', telefono: '9876543210', password:"654321"},
    //{_id: '4', nombre: 'xxx', tipo: "Comerciante", correo: 'xxx@correo.com', telefono: '9876543210', password:"1234567"},
    {_id: '3', nombre: 'usuario 3', tipo: "Comerciante", correo: 'tres@correo.com', telefono: '0321456987', password:"987456"}
  ]
};
